// ===== Book Data =====
const booksData = {
  "Classic Literature": [
    "Pride and Prejudice – Jane Austen",
    "Moby Dick – Herman Melville",
    "Jane Eyre – Charlotte Brontë",
    "Wuthering Heights – Emily Brontë",
    "Great Expectations – Charles Dickens",
    "Anna Karenina – Leo Tolstoy",
    "Crime and Punishment – Fyodor Dostoevsky",
    "War and Peace – Leo Tolstoy",
    "The Odyssey – Homer",
    "The Iliad – Homer",
    "The Picture of Dorian Gray – Oscar Wilde",
    "Les Misérables – Victor Hugo",
    "Dracula – Bram Stoker",
    "Frankenstein – Mary Shelley",
    "The Scarlet Letter – Nathaniel Hawthorne",
    "The Adventures of Huckleberry Finn – Mark Twain",
    "The Count of Monte Cristo – Alexandre Dumas",
    "Don Quixote – Miguel de Cervantes",
    "A Tale of Two Cities – Charles Dickens",
    "The Brothers Karamazov – Fyodor Dostoevsky",
    "Little Women – Louisa May Alcott",
    "The Time Machine – H.G. Wells",
    "Around the World in 80 Days – Jules Verne",
    "Gulliver’s Travels – Jonathan Swift",
    "Heart of Darkness – Joseph Conrad",
    "Fahrenheit 451 – Ray Bradbury",
    "The Metamorphosis – Franz Kafka",
    "The Grapes of Wrath – John Steinbeck",
    "Of Mice and Men – John Steinbeck",
    "Rebecca – Daphne du Maurier"
  ],

  "Modern Fiction": [
    "The Kite Runner – Khaled Hosseini",
    "Life of Pi – Yann Martel",
    "The Book Thief – Markus Zusak",
    "The Night Circus – Erin Morgenstern",
    "The Alchemist – Paulo Coelho",
    "The Fault in Our Stars – John Green",
    "Gone Girl – Gillian Flynn",
    "The Girl on the Train – Paula Hawkins",
    "A Man Called Ove – Fredrik Backman",
    "The Goldfinch – Donna Tartt",
    "Normal People – Sally Rooney",
    "Eleanor Oliphant is Completely Fine – Gail Honeyman",
    "The Silent Patient – Alex Michaelides",
    "All the Light We Cannot See – Anthony Doerr",
    "The Midnight Library – Matt Haig",
    "It Ends with Us – Colleen Hoover",
    "Verity – Colleen Hoover",
    "Project Hail Mary – Andy Weir",
    "The Seven Husbands of Evelyn Hugo – Taylor Jenkins Reid",
    "Where the Crawdads Sing – Delia Owens",
    "Before We Were Strangers – Renée Carlino",
    "Tomorrow, and Tomorrow, and Tomorrow – Gabrielle Zevin",
    "The House in the Cerulean Sea – TJ Klune",
    "Circe – Madeline Miller",
    "The Song of Achilles – Madeline Miller",
    "Beautiful World, Where Are You – Sally Rooney",
    "Lessons in Chemistry – Bonnie Garmus",
    "The Measure – Nikki Erlick",
    "Fourth Wing – Rebecca Yarros",
    "Iron Flame – Rebecca Yarros"
  ],

  "Science Fiction": [
    "Dune – Frank Herbert",
    "Neuromancer – William Gibson",
    "Foundation – Isaac Asimov",
    "I, Robot – Isaac Asimov",
    "Ender’s Game – Orson Scott Card",
    "Snow Crash – Neal Stephenson",
    "The Martian – Andy Weir",
    "Ready Player One – Ernest Cline",
    "Hyperion – Dan Simmons",
    "The Left Hand of Darkness – Ursula K. Le Guin",
    "Brave New World – Aldous Huxley",
    "1984 – George Orwell",
    "Do Androids Dream of Electric Sheep? – Philip K. Dick",
    "Altered Carbon – Richard K. Morgan",
    "The Forever War – Joe Haldeman",
    "Red Mars – Kim Stanley Robinson",
    "The Three-Body Problem – Liu Cixin",
    "Contact – Carl Sagan",
    "Starship Troopers – Robert A. Heinlein",
    "Old Man’s War – John Scalzi",
    "Children of Time – Adrian Tchaikovsky",
    "Project Hail Mary – Andy Weir",
    "The Hunger Games – Suzanne Collins",
    "Divergent – Veronica Roth",
    "Catching Fire – Suzanne Collins",
    "Mockingjay – Suzanne Collins",
    "Recursion – Blake Crouch",
    "Dark Matter – Blake Crouch",
    "The Andromeda Strain – Michael Crichton",
    "Jurassic Park – Michael Crichton"
  ],

  "Fantasy": [
    "Harry Potter and the Sorcerer’s Stone – J.K. Rowling",
    "Harry Potter and the Chamber of Secrets – J.K. Rowling",
    "Harry Potter and the Prisoner of Azkaban – J.K. Rowling",
    "Harry Potter and the Goblet of Fire – J.K. Rowling",
    "Harry Potter and the Order of the Phoenix – J.K. Rowling",
    "Harry Potter and the Half-Blood Prince – J.K. Rowling",
    "Harry Potter and the Deathly Hallows – J.K. Rowling",
    "The Hobbit – J.R.R. Tolkien",
    "The Fellowship of the Ring – J.R.R. Tolkien",
    "The Two Towers – J.R.R. Tolkien",
    "The Return of the King – J.R.R. Tolkien",
    "A Game of Thrones – George R.R. Martin",
    "A Clash of Kings – George R.R. Martin",
    "A Storm of Swords – George R.R. Martin",
    "A Feast for Crows – George R.R. Martin",
    "A Dance with Dragons – George R.R. Martin",
    "Mistborn – Brandon Sanderson",
    "The Final Empire – Brandon Sanderson",
    "The Well of Ascension – Brandon Sanderson",
    "The Hero of Ages – Brandon Sanderson",
    "The Name of the Wind – Patrick Rothfuss",
    "The Wise Man’s Fear – Patrick Rothfuss",
    "The Way of Kings – Brandon Sanderson",
    "Words of Radiance – Brandon Sanderson",
    "Oathbringer – Brandon Sanderson",
    "The Lies of Locke Lamora – Scott Lynch",
    "The Blade Itself – Joe Abercrombie",
    "The Last Wish – Andrzej Sapkowski",
    "Sword of Destiny – Andrzej Sapkowski",
    "Blood of Elves – Andrzej Sapkowski"
  ],

  "Mystery & Thriller": [
    "The Da Vinci Code – Dan Brown",
    "Angels & Demons – Dan Brown",
    "Inferno – Dan Brown",
    "Origin – Dan Brown",
    "The Lost Symbol – Dan Brown",
    "Gone Girl – Gillian Flynn",
    "Sharp Objects – Gillian Flynn",
    "Dark Places – Gillian Flynn",
    "The Girl with the Dragon Tattoo – Stieg Larsson",
    "The Girl Who Played with Fire – Stieg Larsson",
    "The Girl Who Kicked the Hornet’s Nest – Stieg Larsson",
    "Big Little Lies – Liane Moriarty",
    "Nine Perfect Strangers – Liane Moriarty",
    "The Couple Next Door – Shari Lapena",
    "An Unwanted Guest – Shari Lapena",
    "The Silent Patient – Alex Michaelides",
    "The Woman in the Window – A.J. Finn",
    "The Family Upstairs – Lisa Jewell",
    "Watching You – Lisa Jewell",
    "None of This is True – Lisa Jewell",
    "In the Woods – Tana French",
    "The Likeness – Tana French",
    "Faithful Place – Tana French",
    "The Secret Place – Tana French",
    "The Trespasser – Tana French",
    "Before She Knew Him – Peter Swanson",
    "Every Vow You Break – Peter Swanson",
    "Eight Perfect Murders – Peter Swanson",
    "The Kind Worth Killing – Peter Swanson",
    "A Slow Fire Burning – Paula Hawkins"
  ],

  "Romance": [
    "Pride and Prejudice – Jane Austen",
    "Me Before You – Jojo Moyes",
    "After You – Jojo Moyes",
    "Still Me – Jojo Moyes",
    "The Notebook – Nicholas Sparks",
    "Message in a Bottle – Nicholas Sparks",
    "Dear John – Nicholas Sparks",
    "The Longest Ride – Nicholas Sparks",
    "Safe Haven – Nicholas Sparks",
    "The Lucky One – Nicholas Sparks",
    "The Wedding – Nicholas Sparks",
    "One Day – David Nicholls",
    "The Time Traveler’s Wife – Audrey Niffenegger",
    "The Rosie Project – Graeme Simsion",
    "The Rosie Effect – Graeme Simsion",
    "It Ends with Us – Colleen Hoover",
    "It Starts with Us – Colleen Hoover",
    "Ugly Love – Colleen Hoover",
    "Reminders of Him – Colleen Hoover",
    "November 9 – Colleen Hoover",
    "Verity – Colleen Hoover",
    "Hopeless – Colleen Hoover",
    "Confess – Colleen Hoover",
    "Slammed – Colleen Hoover",
    "Losing Hope – Colleen Hoover",
    "All Your Perfects – Colleen Hoover",
    "Heart Bones – Colleen Hoover",
    "Regretting You – Colleen Hoover",
    "Maybe Someday – Colleen Hoover",
    "Finding Perfect – Colleen Hoover"
  ],

  "Non-Fiction": [
    "Sapiens – Yuval Noah Harari",
    "Homo Deus – Yuval Noah Harari",
    "21 Lessons for the 21st Century – Yuval Noah Harari",
    "Educated – Tara Westover",
    "Becoming – Michelle Obama",
    "Atomic Habits – James Clear",
    "The Power of Habit – Charles Duhigg",
    "Thinking, Fast and Slow – Daniel Kahneman",
    "Outliers – Malcolm Gladwell",
    "Blink – Malcolm Gladwell",
    "Talking to Strangers – Malcolm Gladwell",
    "The Tipping Point – Malcolm Gladwell",
    "Can’t Hurt Me – David Goggins",
    "Never Finished – David Goggins",
    "Born a Crime – Trevor Noah",
    "Steve Jobs – Walter Isaacson",
    "Elon Musk – Walter Isaacson",
    "The Subtle Art of Not Giving a F*ck – Mark Manson",
    "Everything is F*cked – Mark Manson",
    "The 48 Laws of Power – Robert Greene",
    "The Laws of Human Nature – Robert Greene",
    "Mastery – Robert Greene",
    "The Art of War – Sun Tzu",
    "Man’s Search for Meaning – Viktor E. Frankl",
    "Meditations – Marcus Aurelius",
    "The 7 Habits of Highly Effective People – Stephen Covey",
    "Deep Work – Cal Newport",
    "So Good They Can’t Ignore You – Cal Newport",
    "Start with Why – Simon Sinek",
    "Leaders Eat Last – Simon Sinek"
  ],

  "Biography": [
    "Steve Jobs – Walter Isaacson",
    "Elon Musk – Walter Isaacson",
    "Becoming – Michelle Obama",
    "The Diary of a Young Girl – Anne Frank",
    "Long Walk to Freedom – Nelson Mandela",
    "The Story of My Experiments with Truth – Mahatma Gandhi",
    "The Autobiography of Malcolm X – Malcolm X",
    "I Am Malala – Malala Yousafzai",
    "Educated – Tara Westover",
    "The Glass Castle – Jeannette Walls",
    "Open – Andre Agassi",
    "Born a Crime – Trevor Noah",
    "My Life in Full – Indra Nooyi",
    "A Promised Land – Barack Obama",
    "Spare – Prince Harry",
    "Becoming – Michelle Obama",
    "Einstein – Walter Isaacson",
    "Leonardo da Vinci – Walter Isaacson",
    "Churchill – Andrew Roberts",
    "Alexander Hamilton – Ron Chernow",
    "Titan – Ron Chernow",
    "The Wright Brothers – David McCullough",
    "Truman – David McCullough",
    "John Adams – David McCullough",
    "Benjamin Franklin – Walter Isaacson",
    "Madam Curie – Eve Curie",
    "Steve Jobs – Walter Isaacson",
    "When Breath Becomes Air – Paul Kalanithi",
    "Educated – Tara Westover",
    "Becoming – Michelle Obama"
  ]
};

// ===== Populate Genres =====
document.addEventListener("DOMContentLoaded", () => {
  const genreSelect = document.getElementById("genre");
  if (!genreSelect) return;

  Object.keys(booksData).forEach((genre) => {
    const option = document.createElement("option");
    option.value = genre;
    option.textContent = genre;
    genreSelect.appendChild(option);
  });
});

// ===== Populate Books =====
function populateBooks() {
  const genre = document.getElementById("genre").value;
  const bookSelect = document.getElementById("book");
  bookSelect.innerHTML = "<option value=''>Select Book</option>";

  if (genre && booksData[genre]) {
    booksData[genre].forEach((book) => {
      const option = document.createElement("option");
      option.value = book;
      option.textContent = book;
      bookSelect.appendChild(option);
    });
  }
}
